name: block
channels:
  - defaults
dependencies:
  - anyio=3.5.0=py39hca03da5_0
  - appnope=0.1.2=py39hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h1a28f6b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39hca03da5_0
  - black=22.6.0=py39hca03da5_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py39h1a28f6b_1002
  - ca-certificates=2022.07.19=hca03da5_0
  - certifi=2022.6.15=py39hca03da5_0
  - cffi=1.15.1=py39h22df2f2_0
  - click=8.0.4=py39hca03da5_0
  - cryptography=37.0.1=py39h834c97f_0
  - debugpy=1.5.1=py39hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ipykernel=6.15.2=py39hca03da5_0
  - ipython=8.4.0=py39hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py39hca03da5_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jupyter_client=7.3.5=py39hca03da5_0
  - jupyter_core=4.10.0=py39hca03da5_0
  - jupyter_server=1.18.1=py39hca03da5_0
  - jupyterlab=3.4.4=py39hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.12.0=py39hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.2=hc377ac9_4
  - libsodium=1.0.18=h1a28f6b_0
  - markupsafe=2.1.1=py39h1a28f6b_0
  - matplotlib-inline=0.1.6=py39hca03da5_0
  - mistune=0.8.4=py39h1a28f6b_1000
  - mypy_extensions=0.4.3=py39hca03da5_1
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py39hca03da5_0
  - nbconvert=6.4.4=py39hca03da5_0
  - nbformat=5.3.0=py39hca03da5_0
  - ncurses=6.3=h1a28f6b_3
  - nest-asyncio=1.5.5=py39hca03da5_0
  - notebook=6.4.12=py39hca03da5_0
  - openssl=1.1.1q=h1a28f6b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.9.0=py39hca03da5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py39hca03da5_0
  - platformdirs=2.5.2=py39hca03da5_0
  - prometheus_client=0.14.1=py39hca03da5_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py39h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.13=hbdb9e5c_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39hca03da5_0
  - pytz=2022.1=py39hca03da5_0
  - pyzmq=23.2.0=py39hc377ac9_0
  - readline=8.1.2=h1a28f6b_1
  - requests=2.28.1=py39hca03da5_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=63.4.1=py39hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39hca03da5_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.39.2=h1058600_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py39hca03da5_0
  - testpath=0.6.0=py39hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=py39hca03da5_0
  - tornado=6.2=py39h1a28f6b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py39hca03da5_0
  - typing_extensions=4.3.0=py39hca03da5_0
  - tzdata=2022c=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hca03da5_1
  - websocket-client=0.58.0=py39hca03da5_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1a28f6b_1
  - zeromq=4.3.4=hc377ac9_0
  - zlib=1.2.12=h5a0b063_3
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - base58==2.1.1
    - bitarray==2.6.0
    - charset-normalizer==2.1.1
    - cytoolz==0.12.0
    - eth-abi==2.2.0
    - eth-account==0.5.9
    - eth-hash==0.5.0
    - eth-keyfile==0.5.1
    - eth-keys==0.3.4
    - eth-rlp==0.2.1
    - eth-typing==2.3.0
    - eth-utils==1.9.5
    - frozenlist==1.3.1
    - hexbytes==0.3.0
    - idna==3.4
    - ipfshttpclient==0.8.0a2
    - jsonschema==4.16.0
    - lru-dict==1.1.8
    - multiaddr==0.0.9
    - multidict==6.0.2
    - netaddr==0.8.0
    - parsimonious==0.8.1
    - protobuf==3.20.2
    - py-solc-x==1.1.1
    - pycryptodome==3.15.0
    - pyrsistent==0.18.1
    - python-dotenv==0.21.0
    - rlp==2.0.1
    - semantic-version==2.10.0
    - toolz==0.12.0
    - urllib3==1.26.12
    - varint==1.0.2
    - web3==5.30.0
    - websockets==9.1
    - yarl==1.8.1
prefix: /opt/anaconda3/envs/block
